#!/usr/bin/env python3
"""
Evaluate original ChordEdit SD-Turbo ablation outputs.

This is a reproduction-style evaluator for the 20-sample or 700-sample
ablation outputs generated by:

  run_original_sd_turbo_all_ablations_pilot.sh

It computes:
  - MSE
  - PSNR
  - simple SSIM
  - CLIP source similarity
  - CLIP target similarity
  - directional CLIP edit similarity

Outputs:
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/all_ablation_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/table2_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/delta_sweep_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/tstart_sweep_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/tend_sweep_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/lambda_sweep_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/noise_sweep_metrics.csv
  /shared/ssd_30T/zarageddes/chordedit_original_ablations/results/steps_sweep_metrics.csv
"""

from __future__ import annotations

import csv
import json
import math
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import torch
from PIL import Image
from transformers import CLIPModel, CLIPProcessor


PIE_ROOT = Path.home() / "datasets/PIE-Bench_v1"
EXPORT_ROOT = Path("/shared/ssd_30T/zarageddes/chordedit_original_ablations")
OUTPUT_ROOT = EXPORT_ROOT / "output"
RESULTS_ROOT = EXPORT_ROOT / "results"

MAPPING_PATH = PIE_ROOT / "mapping_file.json"
SOURCE_IMAGE_ROOT = PIE_ROOT / "annotation_images"

CLIP_MODEL_NAME = "openai/clip-vit-base-patch32"
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

ABLATION_PATTERN = re.compile(r"(table2_|sweep_|noise_|steps_)")


def load_mapping() -> Dict[str, dict]:
    with open(MAPPING_PATH, "r") as f:
        return json.load(f)


def pil_to_np(path: Path, size: Optional[Tuple[int, int]] = None) -> np.ndarray:
    image = Image.open(path).convert("RGB")
    if size is not None:
        image = image.resize(size, Image.BICUBIC)
    arr = np.asarray(image).astype(np.float32) / 255.0
    return arr


def mse_psnr_ssim(src: np.ndarray, out: np.ndarray) -> Tuple[float, float, float]:
    mse = float(np.mean((src - out) ** 2))
    psnr = 99.0 if mse <= 1e-12 else float(10.0 * math.log10(1.0 / mse))

    # Simple global SSIM approximation.
    # This is not a perfect replacement for official PIE-Bench SSIM,
    # but it is stable for pilot comparisons.
    x = src.mean(axis=2)
    y = out.mean(axis=2)

    mu_x = float(x.mean())
    mu_y = float(y.mean())
    var_x = float(x.var())
    var_y = float(y.var())
    cov_xy = float(((x - mu_x) * (y - mu_y)).mean())

    c1 = 0.01 ** 2
    c2 = 0.03 ** 2
    denom = (mu_x ** 2 + mu_y ** 2 + c1) * (var_x + var_y + c2)
    ssim = 1.0 if denom == 0 else ((2 * mu_x * mu_y + c1) * (2 * cov_xy + c2)) / denom
    return mse, psnr, float(ssim)


def load_clip():
    print(f"Loading CLIP model: {CLIP_MODEL_NAME} on {DEVICE}")
    processor = CLIPProcessor.from_pretrained(CLIP_MODEL_NAME, use_safetensors=True)
    model = CLIPModel.from_pretrained(CLIP_MODEL_NAME, use_safetensors=True).to(DEVICE)
    model.eval()
    return processor, model


@torch.no_grad()
def clip_image_features(paths: List[Path], processor, model, batch_size: int = 16) -> torch.Tensor:
    feats = []
    for i in range(0, len(paths), batch_size):
        batch_paths = paths[i : i + batch_size]
        images = [Image.open(p).convert("RGB") for p in batch_paths]
        inputs = processor(images=images, return_tensors="pt", padding=True).to(DEVICE)
        emb = model.get_image_features(**inputs)
        emb = emb / emb.norm(dim=-1, keepdim=True)
        feats.append(emb.detach().cpu())
    return torch.cat(feats, dim=0)


@torch.no_grad()
def clip_text_features(texts: List[str], processor, model, batch_size: int = 64) -> torch.Tensor:
    feats = []
    for i in range(0, len(texts), batch_size):
        batch_texts = texts[i : i + batch_size]
        inputs = processor(text=batch_texts, return_tensors="pt", padding=True, truncation=True).to(DEVICE)
        emb = model.get_text_features(**inputs)
        emb = emb / emb.norm(dim=-1, keepdim=True)
        feats.append(emb.detach().cpu())
    return torch.cat(feats, dim=0)


def method_group(method_name: str) -> str:
    if method_name.startswith("table2_"):
        return "table2"
    if method_name.startswith("sweep_delta_"):
        return "delta_sweep"
    if method_name.startswith("sweep_tstart_"):
        return "tstart_sweep"
    if method_name.startswith("sweep_tend_"):
        return "tend_sweep"
    if method_name.startswith("sweep_lambda_"):
        return "lambda_sweep"
    if method_name.startswith("noise_"):
        return "noise_sweep"
    if method_name.startswith("steps_"):
        return "steps_sweep"
    return "other"


def method_sort_key(name: str):
    nums = re.findall(r"\d+", name)
    parsed_nums = tuple(int(x) for x in nums)
    return (method_group(name), name, parsed_nums)


def collect_method_images(method_dir: Path) -> List[Path]:
    return sorted(method_dir.rglob("*.jpg"))


def rel_key_from_generated(path: Path) -> str:
    # Generated:
    # output/<method>/annotation_images/<chord_folder>/0_random_140/000000000000.jpg
    #
    # Match using:
    # 0_random_140/000000000000.jpg
    return str(Path(path.parent.name) / path.name)


def eval_method(method_dir: Path, mapping: Dict[str, dict], processor, clip_model) -> Optional[dict]:
    method_name = method_dir.name
    image_paths = collect_method_images(method_dir)

    if not image_paths:
        print(f"WARNING: no jpg images found for {method_name}")
        return None

    valid_generated: List[Path] = []
    valid_source: List[Path] = []
    original_prompts: List[str] = []
    editing_prompts: List[str] = []

    mse_vals = []
    psnr_vals = []
    ssim_vals = []

    for gen_path in image_paths:
        rel_key = rel_key_from_generated(gen_path)
        image_id = Path(rel_key).stem

        if image_id not in mapping:
            print(f"WARNING: {method_name}: image id not in mapping: {image_id}")
            continue

        item = mapping[image_id]
        source_rel = item["image_path"]
        source_path = SOURCE_IMAGE_ROOT / source_rel

        if not source_path.exists():
            print(f"WARNING: source image missing: {source_path}")
            continue

        out_img = Image.open(gen_path).convert("RGB")
        out_size = out_img.size
        src_np = pil_to_np(source_path, size=out_size)
        out_np = np.asarray(out_img).astype(np.float32) / 255.0

        mse, psnr, ssim = mse_psnr_ssim(src_np, out_np)
        mse_vals.append(mse)
        psnr_vals.append(psnr)
        ssim_vals.append(ssim)

        valid_generated.append(gen_path)
        valid_source.append(source_path)
        original_prompts.append(item["original_prompt"])
        editing_prompts.append(item["editing_prompt"])

    if not valid_generated:
        print(f"WARNING: no valid matched images for {method_name}")
        return None

    print(f"Evaluating CLIP for {method_name}: {len(valid_generated)} images")

    gen_img_feat = clip_image_features(valid_generated, processor, clip_model)
    src_img_feat = clip_image_features(valid_source, processor, clip_model)
    src_txt_feat = clip_text_features(original_prompts, processor, clip_model)
    edit_txt_feat = clip_text_features(editing_prompts, processor, clip_model)

    clip_source = torch.sum(gen_img_feat * src_txt_feat, dim=-1)
    clip_target = torch.sum(gen_img_feat * edit_txt_feat, dim=-1)

    img_direction = gen_img_feat - src_img_feat
    txt_direction = edit_txt_feat - src_txt_feat
    img_direction = img_direction / img_direction.norm(dim=-1, keepdim=True).clamp_min(1e-8)
    txt_direction = txt_direction / txt_direction.norm(dim=-1, keepdim=True).clamp_min(1e-8)
    clip_edit_direction = torch.sum(img_direction * txt_direction, dim=-1)

    return {
        "method": method_name,
        "group": method_group(method_name),
        "num_images": len(valid_generated),
        "mse": float(np.mean(mse_vals)),
        "psnr": float(np.mean(psnr_vals)),
        "ssim": float(np.mean(ssim_vals)),
        "clip_source": float(clip_source.mean().item()),
        "clip_target": float(clip_target.mean().item()),
        "clip_edit_direction": float(clip_edit_direction.mean().item()),
    }


def write_csv(path: Path, rows: List[dict]) -> None:
    if not rows:
        return

    path.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = [
        "method",
        "group",
        "num_images",
        "mse",
        "psnr",
        "ssim",
        "clip_source",
        "clip_target",
        "clip_edit_direction",
    ]

    with open(path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    print(f"Wrote {path}")


def main() -> None:
    RESULTS_ROOT.mkdir(parents=True, exist_ok=True)

    mapping = load_mapping()

    method_dirs = [
        p for p in OUTPUT_ROOT.iterdir()
        if p.is_dir() and ABLATION_PATTERN.search(p.name)
    ]
    method_dirs = sorted(method_dirs, key=lambda p: method_sort_key(p.name))

    print(f"Found {len(method_dirs)} ablation method folders")
    for p in method_dirs:
        print(f"  {p.name}")

    processor, clip_model = load_clip()

    rows = []
    for method_dir in method_dirs:
        row = eval_method(method_dir, mapping, processor, clip_model)
        if row is not None:
            rows.append(row)

    rows = sorted(rows, key=lambda r: method_sort_key(r["method"]))

    write_csv(RESULTS_ROOT / "all_ablation_metrics.csv", rows)

    for group in [
        "table2",
        "delta_sweep",
        "tstart_sweep",
        "tend_sweep",
        "lambda_sweep",
        "noise_sweep",
        "steps_sweep",
    ]:
        group_rows = [r for r in rows if r["group"] == group]
        write_csv(RESULTS_ROOT / f"{group}_metrics.csv", group_rows)

    print()
    print("Done.")
    print(f"Results are under: {RESULTS_ROOT}")


if __name__ == "__main__":
    main()